/**
 * Countries list with ISO codes, names, and ISD codes
 * Based on ISO 3166-1 alpha-2 country codes
 */
export const countries = [
  { code: 'US', name: 'United States', isd: '+1' },
  { code: 'GB', name: 'United Kingdom', isd: '+44' },
  { code: 'CA', name: 'Canada', isd: '+1' },
  { code: 'AU', name: 'Australia', isd: '+61' },
  { code: 'DE', name: 'Germany', isd: '+49' },
  { code: 'FR', name: 'France', isd: '+33' },
  { code: 'IT', name: 'Italy', isd: '+39' },
  { code: 'ES', name: 'Spain', isd: '+34' },
  { code: 'NL', name: 'Netherlands', isd: '+31' },
  { code: 'BE', name: 'Belgium', isd: '+32' },
  { code: 'CH', name: 'Switzerland', isd: '+41' },
  { code: 'AT', name: 'Austria', isd: '+43' },
  { code: 'SE', name: 'Sweden', isd: '+46' },
  { code: 'NO', name: 'Norway', isd: '+47' },
  { code: 'DK', name: 'Denmark', isd: '+45' },
  { code: 'FI', name: 'Finland', isd: '+358' },
  { code: 'PL', name: 'Poland', isd: '+48' },
  { code: 'CZ', name: 'Czech Republic', isd: '+420' },
  { code: 'GR', name: 'Greece', isd: '+30' },
  { code: 'PT', name: 'Portugal', isd: '+351' },
  { code: 'IE', name: 'Ireland', isd: '+353' },
  { code: 'NZ', name: 'New Zealand', isd: '+64' },
  { code: 'JP', name: 'Japan', isd: '+81' },
  { code: 'CN', name: 'China', isd: '+86' },
  { code: 'IN', name: 'India', isd: '+91' },
  { code: 'KR', name: 'South Korea', isd: '+82' },
  { code: 'SG', name: 'Singapore', isd: '+65' },
  { code: 'MY', name: 'Malaysia', isd: '+60' },
  { code: 'TH', name: 'Thailand', isd: '+66' },
  { code: 'PH', name: 'Philippines', isd: '+63' },
  { code: 'ID', name: 'Indonesia', isd: '+62' },
  { code: 'VN', name: 'Vietnam', isd: '+84' },
  { code: 'AE', name: 'United Arab Emirates', isd: '+971' },
  { code: 'SA', name: 'Saudi Arabia', isd: '+966' },
  { code: 'IL', name: 'Israel', isd: '+972' },
  { code: 'TR', name: 'Turkey', isd: '+90' },
  { code: 'EG', name: 'Egypt', isd: '+20' },
  { code: 'ZA', name: 'South Africa', isd: '+27' },
  { code: 'BR', name: 'Brazil', isd: '+55' },
  { code: 'MX', name: 'Mexico', isd: '+52' },
  { code: 'AR', name: 'Argentina', isd: '+54' },
  { code: 'CL', name: 'Chile', isd: '+56' },
  { code: 'CO', name: 'Colombia', isd: '+57' },
  { code: 'PE', name: 'Peru', isd: '+51' },
  { code: 'VE', name: 'Venezuela', isd: '+58' },
  { code: 'RU', name: 'Russia', isd: '+7' },
  { code: 'UA', name: 'Ukraine', isd: '+380' },
  { code: 'PK', name: 'Pakistan', isd: '+92' },
  { code: 'BD', name: 'Bangladesh', isd: '+880' },
  { code: 'LK', name: 'Sri Lanka', isd: '+94' },
  { code: 'NP', name: 'Nepal', isd: '+977' },
  { code: 'AF', name: 'Afghanistan', isd: '+93' },
  { code: 'IQ', name: 'Iraq', isd: '+964' },
  { code: 'IR', name: 'Iran', isd: '+98' },
  { code: 'KW', name: 'Kuwait', isd: '+965' },
  { code: 'QA', name: 'Qatar', isd: '+974' },
  { code: 'BH', name: 'Bahrain', isd: '+973' },
  { code: 'OM', name: 'Oman', isd: '+968' },
  { code: 'JO', name: 'Jordan', isd: '+962' },
  { code: 'LB', name: 'Lebanon', isd: '+961' },
  { code: 'SY', name: 'Syria', isd: '+963' },
  { code: 'YE', name: 'Yemen', isd: '+967' },
  { code: 'KE', name: 'Kenya', isd: '+254' },
  { code: 'NG', name: 'Nigeria', isd: '+234' },
  { code: 'GH', name: 'Ghana', isd: '+233' },
  { code: 'ET', name: 'Ethiopia', isd: '+251' },
  { code: 'TZ', name: 'Tanzania', isd: '+255' },
  { code: 'UG', name: 'Uganda', isd: '+256' },
  { code: 'MA', name: 'Morocco', isd: '+212' },
  { code: 'DZ', name: 'Algeria', isd: '+213' },
  { code: 'TN', name: 'Tunisia', isd: '+216' },
  { code: 'LY', name: 'Libya', isd: '+218' },
  { code: 'SD', name: 'Sudan', isd: '+249' },
  { code: 'AO', name: 'Angola', isd: '+244' },
  { code: 'MZ', name: 'Mozambique', isd: '+258' },
  { code: 'ZM', name: 'Zambia', isd: '+260' },
  { code: 'ZW', name: 'Zimbabwe', isd: '+263' },
  { code: 'BW', name: 'Botswana', isd: '+267' },
  { code: 'NA', name: 'Namibia', isd: '+264' },
  { code: 'MU', name: 'Mauritius', isd: '+230' },
  { code: 'MG', name: 'Madagascar', isd: '+261' },
  { code: 'RW', name: 'Rwanda', isd: '+250' },
  { code: 'BI', name: 'Burundi', isd: '+257' },
  { code: 'MW', name: 'Malawi', isd: '+265' },
  { code: 'LS', name: 'Lesotho', isd: '+266' },
  { code: 'SZ', name: 'Eswatini', isd: '+268' },
  { code: 'DJ', name: 'Djibouti', isd: '+253' },
  { code: 'ER', name: 'Eritrea', isd: '+291' },
  { code: 'SO', name: 'Somalia', isd: '+252' },
  { code: 'SS', name: 'South Sudan', isd: '+211' },
  { code: 'CM', name: 'Cameroon', isd: '+237' },
  { code: 'SN', name: 'Senegal', isd: '+221' },
  { code: 'CI', name: 'Ivory Coast', isd: '+225' },
  { code: 'ML', name: 'Mali', isd: '+223' },
  { code: 'BF', name: 'Burkina Faso', isd: '+226' },
  { code: 'NE', name: 'Niger', isd: '+227' },
  { code: 'TD', name: 'Chad', isd: '+235' },
  { code: 'CF', name: 'Central African Republic', isd: '+236' },
  { code: 'CG', name: 'Congo', isd: '+242' },
  { code: 'CD', name: 'DR Congo', isd: '+243' },
  { code: 'GA', name: 'Gabon', isd: '+241' },
  { code: 'GQ', name: 'Equatorial Guinea', isd: '+240' },
  { code: 'ST', name: 'São Tomé and Príncipe', isd: '+239' },
  { code: 'GW', name: 'Guinea-Bissau', isd: '+245' },
  { code: 'GN', name: 'Guinea', isd: '+224' },
  { code: 'SL', name: 'Sierra Leone', isd: '+232' },
  { code: 'LR', name: 'Liberia', isd: '+231' },
  { code: 'TG', name: 'Togo', isd: '+228' },
  { code: 'BJ', name: 'Benin', isd: '+229' },
  { code: 'MR', name: 'Mauritania', isd: '+222' },
  { code: 'GM', name: 'Gambia', isd: '+220' },
  { code: 'CV', name: 'Cape Verde', isd: '+238' },
  { code: 'KM', name: 'Comoros', isd: '+269' },
  { code: 'SC', name: 'Seychelles', isd: '+248' },
  { code: 'MV', name: 'Maldives', isd: '+960' },
  { code: 'BT', name: 'Bhutan', isd: '+975' },
  { code: 'MM', name: 'Myanmar', isd: '+95' },
  { code: 'LA', name: 'Laos', isd: '+856' },
  { code: 'KH', name: 'Cambodia', isd: '+855' },
  { code: 'BN', name: 'Brunei', isd: '+673' },
  { code: 'TL', name: 'Timor-Leste', isd: '+670' },
  { code: 'PG', name: 'Papua New Guinea', isd: '+675' },
  { code: 'FJ', name: 'Fiji', isd: '+679' },
  { code: 'NC', name: 'New Caledonia', isd: '+687' },
  { code: 'PF', name: 'French Polynesia', isd: '+689' },
  { code: 'WS', name: 'Samoa', isd: '+685' },
  { code: 'TO', name: 'Tonga', isd: '+676' },
  { code: 'VU', name: 'Vanuatu', isd: '+678' },
  { code: 'SB', name: 'Solomon Islands', isd: '+677' },
  { code: 'KI', name: 'Kiribati', isd: '+686' },
  { code: 'TV', name: 'Tuvalu', isd: '+688' },
  { code: 'NR', name: 'Nauru', isd: '+674' },
  { code: 'PW', name: 'Palau', isd: '+680' },
  { code: 'FM', name: 'Micronesia', isd: '+691' },
  { code: 'MH', name: 'Marshall Islands', isd: '+692' },
  { code: 'AS', name: 'American Samoa', isd: '+1684' },
  { code: 'GU', name: 'Guam', isd: '+1671' },
  { code: 'MP', name: 'Northern Mariana Islands', isd: '+1670' },
  { code: 'VI', name: 'US Virgin Islands', isd: '+1340' },
  { code: 'PR', name: 'Puerto Rico', isd: '+1787' },
  { code: 'DO', name: 'Dominican Republic', isd: '+1809' },
  { code: 'HT', name: 'Haiti', isd: '+509' },
  { code: 'JM', name: 'Jamaica', isd: '+1876' },
  { code: 'CU', name: 'Cuba', isd: '+53' },
  { code: 'BS', name: 'Bahamas', isd: '+1242' },
  { code: 'BB', name: 'Barbados', isd: '+1246' },
  { code: 'TT', name: 'Trinidad and Tobago', isd: '+1868' },
  { code: 'GD', name: 'Grenada', isd: '+1473' },
  { code: 'LC', name: 'Saint Lucia', isd: '+1758' },
  { code: 'VC', name: 'Saint Vincent', isd: '+1784' },
  { code: 'AG', name: 'Antigua and Barbuda', isd: '+1268' },
  { code: 'DM', name: 'Dominica', isd: '+1767' },
  { code: 'KN', name: 'Saint Kitts and Nevis', isd: '+1869' },
  { code: 'BZ', name: 'Belize', isd: '+501' },
  { code: 'GT', name: 'Guatemala', isd: '+502' },
  { code: 'SV', name: 'El Salvador', isd: '+503' },
  { code: 'HN', name: 'Honduras', isd: '+504' },
  { code: 'NI', name: 'Nicaragua', isd: '+505' },
  { code: 'CR', name: 'Costa Rica', isd: '+506' },
  { code: 'PA', name: 'Panama', isd: '+507' },
  { code: 'UY', name: 'Uruguay', isd: '+598' },
  { code: 'PY', name: 'Paraguay', isd: '+595' },
  { code: 'BO', name: 'Bolivia', isd: '+591' },
  { code: 'EC', name: 'Ecuador', isd: '+593' },
  { code: 'GY', name: 'Guyana', isd: '+592' },
  { code: 'SR', name: 'Suriname', isd: '+597' },
  { code: 'GF', name: 'French Guiana', isd: '+594' },
  { code: 'FK', name: 'Falkland Islands', isd: '+500' },
  { code: 'GS', name: 'South Georgia', isd: '+500' },
  { code: 'IS', name: 'Iceland', isd: '+354' },
  { code: 'FO', name: 'Faroe Islands', isd: '+298' },
  { code: 'GL', name: 'Greenland', isd: '+299' },
  { code: 'SJ', name: 'Svalbard', isd: '+47' },
  { code: 'EE', name: 'Estonia', isd: '+372' },
  { code: 'LV', name: 'Latvia', isd: '+371' },
  { code: 'LT', name: 'Lithuania', isd: '+370' },
  { code: 'BY', name: 'Belarus', isd: '+375' },
  { code: 'MD', name: 'Moldova', isd: '+373' },
  { code: 'RO', name: 'Romania', isd: '+40' },
  { code: 'BG', name: 'Bulgaria', isd: '+359' },
  { code: 'RS', name: 'Serbia', isd: '+381' },
  { code: 'ME', name: 'Montenegro', isd: '+382' },
  { code: 'BA', name: 'Bosnia and Herzegovina', isd: '+387' },
  { code: 'HR', name: 'Croatia', isd: '+385' },
  { code: 'SI', name: 'Slovenia', isd: '+386' },
  { code: 'SK', name: 'Slovakia', isd: '+421' },
  { code: 'HU', name: 'Hungary', isd: '+36' },
  { code: 'AL', name: 'Albania', isd: '+355' },
  { code: 'MK', name: 'North Macedonia', isd: '+389' },
  { code: 'XK', name: 'Kosovo', isd: '+383' },
  { code: 'MT', name: 'Malta', isd: '+356' },
  { code: 'CY', name: 'Cyprus', isd: '+357' },
  { code: 'LU', name: 'Luxembourg', isd: '+352' },
  { code: 'LI', name: 'Liechtenstein', isd: '+423' },
  { code: 'MC', name: 'Monaco', isd: '+377' },
  { code: 'AD', name: 'Andorra', isd: '+376' },
  { code: 'SM', name: 'San Marino', isd: '+378' },
  { code: 'VA', name: 'Vatican City', isd: '+39' },
  { code: 'KZ', name: 'Kazakhstan', isd: '+7' },
  { code: 'UZ', name: 'Uzbekistan', isd: '+998' },
  { code: 'TM', name: 'Turkmenistan', isd: '+993' },
  { code: 'TJ', name: 'Tajikistan', isd: '+992' },
  { code: 'KG', name: 'Kyrgyzstan', isd: '+996' },
  { code: 'MN', name: 'Mongolia', isd: '+976' },
  { code: 'KP', name: 'North Korea', isd: '+850' },
  { code: 'TW', name: 'Taiwan', isd: '+886' },
  { code: 'HK', name: 'Hong Kong', isd: '+852' },
  { code: 'MO', name: 'Macau', isd: '+853' },
  { code: 'BN', name: 'Brunei', isd: '+673' },
].sort((a, b) => a.name.localeCompare(b.name));
